BaseUrl= "https://turq.io/"
LanguageCode= "en-US"
Title= "Turq"
theme = "hugo-cards"
paginate = 6
themesDir = "./themes"

[params]
  homeSubtitle="Legislation for the people, by the people"
  builtBy = "bool"
  defaultImage = "turq_logo.PNG"
  defaultImageInverse = "turq_logo_inverse.PNG"

  facebook = ""
  quora = ""
  twitter = ""
  github = ""
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""
