backend:
  name: git-gateway
  repo: TurqPBC/turqV2
  branch: staging

media_library:
  name: 'disabled'
media_folder: "static/images" # Media files will be stored in the repo under images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
display_url: https://turq.io/
collections:
  - name: "Draft-Legislation" # Used in routes, e.g., /admin/collections/blog
    label: "Draft Legislation" # Used in the UI
    folder: "content/legislation" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: false
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Official Title", hint: "The name of the legislation. Ex. An Act Establishing Financial Literacy Education In Massachusetts", name: "title", widget: "string"}

      - {label: "What Chapter of the General Laws Do You Want to Modify?", hint: "Ex. Chapter 69 of the General Law is hereby amended by inserting the following after section 1Q the following section::", name: "chapter", widget: "string"}

      - {label: "General Laws Section", hint: "If you want to modify a Section of that Chapter, provide the number below. If you want to add a Section to the Chapter, give it a number below. Provide a Title for the new Section. Ex. Section 1R. Financial Literacy Education in Massachusetts", name: "section", widget: "string"}

      - {label: "Describe what this bill accomplishes in 1-2 sentences", hint: "Ex. This document specifies minimum requirements for the implementation of a financial literacy education program in the public schools of the Commonwealth of Massachusetts.", name: "accomplishes", widget: "string"}

      - {label: "Define the terms you will be using in this legislation", hint: "Ex. Public School - A school that is located in the Commonwealth of Massachusetts and maintained at public expense...\nPrivate School - A school that is located in the Commonwealth of Massachusetts and privately funded through parent paid tuition charges or sponsored by organizations...", name: "terms", widget: "text"}

      - {label: "Statement of Purpose (expand and go deeper on Bill description)", hint: "Ex. This legislation commissions the creation of an opt-in voluntary study..  allow the ongoing, long-term collection of financial health and satisfaction metrics as defined by the study authors...", name: "purpose", widget: "text"}

      - {label: "Provisions", hint: "Ex. This legislation applies to all Massachusetts Public and Charter Schools that receive public federal funding in the Commonwealth of Massachusetts...", name: "provisions", widget: "text"}

      - {label: "Special Exceptions", hint: "Ex. Private Schools are exempt from this legislation.Special Education curriculum and instruction are exempt from this legislation.", name: "exceptions", widget: "string", required: false}

      - {label: "Other Provisions", hint: "Ex. A position on the Massachusetts State Board of Education shall be created to act as a liaison between the United States Department of Education and other State Boards of Education as it pertains to the education of financial literacy...", name: "other", widget: "string", required: false}
      - {label: "competition", hint: "competition", name: "competition", widget: "hidden"}
  - name: "Competitions" # Used in routes, e.g., /admin/collections/blog
    label: "Competitions" # Used in the UI
    folder: "content/competition" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: false
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", hint: "Name of the competition", name: "title", widget: "string"}
      - label: "End Date"
        name: "endDate"
        widget: "date"
        default: ""
        format: "x"
      - {label: "Prizes", hint: "Prizes rewared for this competition", name: "prizes", widget: "text"}
      - {label: "Description", hint: "Please note that will section headers do not appear in the preview currently they will be displayed when published so there is no need to add them!", name: "description", widget: "markdown", default: "**Background**\n\n**Timeline**"}
      - {label: "Rules", hint: "Please note that will section headers do not appear in the preview currently they will be displayed when published so there is no need to add them!", name: "rules", widget: "markdown", required: false}
      - {label: "Judging Criteria", hint: "Please note that will section headers do not appear in the preview currently they will be displayed when published so there is no need to add them!", name: "criteria", widget: "markdown", default: "**Initial Screening**\n**Evaluation and Selection**\n* **Technical Merit**\n* **Originality**\n* **Impact**\n* **Practicality**"}
